Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace ContactList.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public ContactLoginForm LoginForm { get; set; }

        [BindProperty]
        public ContactAddForm AddForm { get; set; }

        public string debug = "";
        public string loggedInUserEmail = "";
        public List<ContactInfo> listContacts = new List<ContactInfo>();
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnPostLogin()
        {            
                loggedInUserEmail = LoginForm.Email;
                showContacts(); 
            return Page();
        }

        public IActionResult OnPostAdd(String email, String password, String firstName,
            String lastName, String category, String subCategory, int phone, String dateOfBirth)
        {
            String connectionString = "Data Source=.\\sqlexpress;Initial Catalog=clients;Integrated Security=True";
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                String deleteQuery = "INSERT INTO Contacts (ContactID, FirstName, LastName, Email, Password, Category, Subcategory, Phone, BirthDate)" +
                    "VALUES (@Id, @FirstName, @LastName, @Email, @Password, @Category, @Subcategory, @Phone, @BirthDate)";
                using (SqlCommand addCommand = new SqlCommand(deleteQuery, connection))
                {
                    addCommand.Parameters.AddWithValue("@Id", ContactInfo.totalContacts+1);
                    addCommand.Parameters.Add("@FirstName", SqlDbType.NVarChar, 255).Value = firstName;
                    addCommand.Parameters.AddWithValue("@LastName", lastName);
                    addCommand.Parameters.AddWithValue("@Email", email);
                    addCommand.Parameters.AddWithValue("@Password", password);
                    addCommand.Parameters.AddWithValue("@Category", category);
                    addCommand.Parameters.AddWithValue("@Subcategory", subCategory);
                    addCommand.Parameters.AddWithValue("@Phone", phone);
                    addCommand.Parameters.AddWithValue("@BirthDate", dateOfBirth);
                    int rowsAffected = addCommand.ExecuteNonQuery();
                }
            }
            showContacts();
            return Page();
        }

        public IActionResult OnPostDelete(int contactId)
        {
            String connectionString = "Data Source=.\\sqlexpress;Initial Catalog=clients;Integrated Security=True";
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                String deleteQuery = "DELETE FROM Contacts WHERE ContactID = @Id";
                using (SqlCommand deleteCommand = new SqlCommand(deleteQuery, connection))
                {
                    deleteCommand.Parameters.AddWithValue("@Id", contactId);
                    int rowsAffected = deleteCommand.ExecuteNonQuery();
                }
            }
            showContacts();
            return Page();
        }

        public IActionResult OnPostDetails(int contactId)
        {
            return Page();
        }

        public void OnGet()
        {
            showContacts();            
        }

        private void showContacts()
        {
            try
            {
                String connectionString = "Data Source=.\\sqlexpress;Initial Catalog=clients;Integrated Security=True";
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();
                    String query = "SELECT * FROM Contacts";
                    using (SqlCommand command = new SqlCommand(query, connection))
                    {
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            ContactInfo.totalContacts = 0;
                            while (reader.Read())
                            {
                                int id = reader.GetInt32(0);
                                string firstName = reader.GetString(1);
                                string lastName = reader.GetString(2);
                                string email = reader.GetString(3);
                                string password = reader.GetString(4);
                                string category = reader.GetString(5);
                                string subCategory = reader.IsDBNull(6) ? null : reader.GetString(6);
                                //int phone = reader.GetInt32(7);                             
                                string birthDate = reader.GetDateTime(8).ToString("yyyy-MM-dd");

                                ContactInfo contactInfo = new ContactInfo(firstName, lastName, email, password, category, subCategory, 111222333, birthDate);
                                listContacts.Add(contactInfo);
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception: " + ex.ToString());
            }            
        }

        public class ContactInfo
        {
            public static int totalContacts = 0;

            public int id;
            public String firstName;
            public String lastName;
            public String email;
            public String password;
            public String category;
            public String subCategory;
            public int phone;
            public String birthDate;

            public ContactInfo(String firstName, String lastName, String email, String password, String category, String subCategory, int phone, String birthDate)
            {
                this.id = ++totalContacts;
                this.firstName = firstName;
                this.lastName = lastName;
                this.email = email;
                this.password = password;
                this.category = category;
                this.subCategory = subCategory;
                this.phone = phone;
                this.birthDate = birthDate;
            }
        }

        public class ContactLoginForm
        {
            [EmailAddress(ErrorMessage = "Invalid Email Address")]
            [Required(ErrorMessage = "Email is required")]
            public string Email { get; set; }

            [Required(ErrorMessage = "Password is required")]
            public string Password { get; set; }
        }

        public class ContactAddForm
        {
            public string Email { get; set; }
            public string Password { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }
            public string Category { get; set; }
            public string Subcategory { get; set; }
            public string DateOfBirth { get; set; }
            public int Phone { get; set; }
        }
    }    
}

Pages/Index.cshtml
@page
@model ContactList.Pages.IndexModel
@{
    ViewData["Title"] = "Contact List";
    String loggedUser = "";
}

@Model.debug

<h2>Contact List</h2>

<div id="logIn">
    <form method="post" asp-page-handler="Login" id="logInForm">
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="LoginForm.Email"></label>
            <input asp-for="LoginForm.Email" class="form-control" />
            <span asp-validation-for="LoginForm.Email" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="LoginForm.Password"></label>
            <input asp-for="LoginForm.Password" type="password" class="form-control" />
            <span asp-validation-for="LoginForm.Password" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <button type="button" id="loginButton" onclick="showLoginForm()">LOG IN</button>
</div>

<table class="table">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th class="detailsHeader">Email</th>
            <th class="detailsHeader">Category</th>
            <th class="detailsHeader">Subcategory</th>
            <th class="detailsHeader">Birth Date</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var contact in Model.listContacts)
        {
            <tr>
                <td>@contact.firstName</td>
                <td>@contact.lastName</td>
                <td class="details">@contact.email</td>
                <td class="details">@contact.category</td>
                <td class="details">@contact.subCategory</td>
                <td class="details">@contact.birthDate</td>
                <td>
                    <form method="post">
                        <input type="hidden" name="contactId" value="@contact" />
                        <button type="button" name="detailsButton" onclick="showDetails(this)">DETAILS</button>
                    </form>
                </td>
                @if (Model.loggedInUserEmail != "")
                {
                    <td>
                        <form method="post" asp-page-handler="Edit" asp-route-contactId="@contact.id">
                            <button type="submit" name="editButton"> EDIT </button>
                        </form>
                    </td>
                    <td>
                        <form method="post" asp-page-handler="Delete" asp-route-contactId="@contact.id">
                            <button type="submit" name="deleteButton">DELETE</button>
                        </form>
                    </td>
                }
            </tr>
        }
        <tr>
            @if (Model.loggedInUserEmail != "")
            {
                <button type="submit" id="addButton" onclick="showAddForm(this)"> ADD NEW CONTACT </button>

                <div id="addForm">
                <form method="post" asp-page-handler="Add">
                    <div asp-validation-summary="All" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="AddForm.Email"></label>
                        <input asp-for="AddForm.Email" class="form-control" />
                        <span asp-validation-for="AddForm.Email" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="AddForm.Password"></label>
                        <input asp-for="AddForm.Password" type="password" class="form-control" />
                        <span asp-validation-for="AddForm.Password" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="AddForm.FirstName"></label>
                        <input asp-for="AddForm.FirstName" class="form-control" />
                        <span asp-validation-for="AddForm.FirstName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="AddForm.LastName"></label>
                        <input asp-for="AddForm.LastName" class="form-control" />
                        <span asp-validation-for="AddForm.LastName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="AddForm.Category"></label>
                        <select asp-for="AddForm.Category" class="form-control">
                            <option value="Category1">Category 1</option>
                            <option value="Category2">Category 2</option>
                        </select>
                        <span asp-validation-for="AddForm.Category" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="AddForm.Subcategory"></label>
                        <input asp-for="AddForm.Subcategory" class="form-control" />
                        <span asp-validation-for="AddForm.Subcategory" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="AddForm.Phone"></label>
                            <input asp-for="AddForm.Phone" class="form-control" />
                            <span asp-validation-for="AddForm.Phone" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="AddForm.DateOfBirth"></label>
                        <input asp-for="AddForm.DateOfBirth" type="date" class="form-control" />
                        <span asp-validation-for="AddForm.DateOfBirth" class="text-danger"></span>
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                </div>
            }
        </tr>
    </tbody>
</table>

<script>
    function showDetails(button) {
        var row = button.closest('tr');
        var detailCells = row.querySelectorAll('.details');

        detailCells.forEach(function (cell) {
            cell.style.display = 'table-cell';
        });

        var headerCells = document.querySelectorAll('.detailsHeader');

        headerCells.forEach(function (cell) {
            cell.style.display = 'table-cell';
        });

        button.disabled = true;
    }

    function showLoginForm() {
        var logInForm = document.getElementById('logInForm');
        logInForm.style.display = 'block';
        document.getElementById("loginButton").style.display = 'none';
    }

    function showAddForm() {
        document.getElementById("addForm").style.display = 'block';
        document.getElementById("addButton").style.display = 'none';
    }
</script>

<style>
    .details {
        display: none;
    }

    .detailsHeader {
        display: none;
    }

    #logInForm {
        display: none;
    }

    #logIn {
        float: right;
    }

    #loginButton {
        display: block;
    }

    #addForm {
        display: none;
    }

    #addButton {
        display: block;
    }
</style>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContactList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ContactList.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ContactList</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ContactList - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>